### ISSUE TITLE
2420 윤시원 강의 2 과제 제출

### ISSUE THREAD

**Issue by ysw421** [Dongyeongkim/intro_to_nn#4]
![KakaoTalk_20231025_153207587](https://github.com/Dongyeongkim/intro_to_nn/assets/63529804/48c06e31-7dc6-441a-a862-97ee19ffca89)
![KakaoTalk_20231025_153232521](https://github.com/Dongyeongkim/intro_to_nn/assets/63529804/5e719627-385f-44ec-b086-2b0c68d6964a)

**Comment by Dongyeongkim** [comment]
수고하셨습니다.
